# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trans_grpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trans_grpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10trans_grpc.proto\"\x8c\x01\n\x0cTransRequest\x12\x11\n\tfrom_lang\x18\x01 \x01(\t\x12\x0f\n\x07to_lang\x18\x02 \x01(\t\x12\x12\n\nquery_text\x18\x03 \x01(\t\x12\x12\n\ntrans_type\x18\x04 \x01(\t\x12\x0c\n\x04mode\x18\x05 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x06 \x01(\t\x12\x12\n\nsecret_key\x18\x07 \x01(\t\"\x1c\n\nTransReply\x12\x0e\n\x06result\x18\x01 \x01(\t2e\n\nTranslater\x12,\n\x0cGetTranslate\x12\r.TransRequest\x1a\x0b.TransReply\"\x00\x12)\n\tTranslate\x12\r.TransRequest\x1a\x0b.TransReply\"\x00\x62\x06proto3')
)




_TRANSREQUEST = _descriptor.Descriptor(
  name='TransRequest',
  full_name='TransRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_lang', full_name='TransRequest.from_lang', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_lang', full_name='TransRequest.to_lang', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query_text', full_name='TransRequest.query_text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trans_type', full_name='TransRequest.trans_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='TransRequest.mode', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_id', full_name='TransRequest.app_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secret_key', full_name='TransRequest.secret_key', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=161,
)


_TRANSREPLY = _descriptor.Descriptor(
  name='TransReply',
  full_name='TransReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='TransReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['TransRequest'] = _TRANSREQUEST
DESCRIPTOR.message_types_by_name['TransReply'] = _TRANSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransRequest = _reflection.GeneratedProtocolMessageType('TransRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSREQUEST,
  '__module__' : 'trans_grpc_pb2'
  # @@protoc_insertion_point(class_scope:TransRequest)
  })
_sym_db.RegisterMessage(TransRequest)

TransReply = _reflection.GeneratedProtocolMessageType('TransReply', (_message.Message,), {
  'DESCRIPTOR' : _TRANSREPLY,
  '__module__' : 'trans_grpc_pb2'
  # @@protoc_insertion_point(class_scope:TransReply)
  })
_sym_db.RegisterMessage(TransReply)



_TRANSLATER = _descriptor.ServiceDescriptor(
  name='Translater',
  full_name='Translater',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=193,
  serialized_end=294,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTranslate',
    full_name='Translater.GetTranslate',
    index=0,
    containing_service=None,
    input_type=_TRANSREQUEST,
    output_type=_TRANSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Translate',
    full_name='Translater.Translate',
    index=1,
    containing_service=None,
    input_type=_TRANSREQUEST,
    output_type=_TRANSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSLATER)

DESCRIPTOR.services_by_name['Translater'] = _TRANSLATER

# @@protoc_insertion_point(module_scope)
