# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import trans_grpc_pb2 as trans__grpc__pb2


class TranslaterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTranslate = channel.unary_unary(
        '/Translater/GetTranslate',
        request_serializer=trans__grpc__pb2.TransRequest.SerializeToString,
        response_deserializer=trans__grpc__pb2.TransReply.FromString,
        )
    self.Translate = channel.unary_unary(
        '/Translater/Translate',
        request_serializer=trans__grpc__pb2.TransRequest.SerializeToString,
        response_deserializer=trans__grpc__pb2.TransReply.FromString,
        )


class TranslaterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTranslate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Translate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TranslaterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTranslate': grpc.unary_unary_rpc_method_handler(
          servicer.GetTranslate,
          request_deserializer=trans__grpc__pb2.TransRequest.FromString,
          response_serializer=trans__grpc__pb2.TransReply.SerializeToString,
      ),
      'Translate': grpc.unary_unary_rpc_method_handler(
          servicer.Translate,
          request_deserializer=trans__grpc__pb2.TransRequest.FromString,
          response_serializer=trans__grpc__pb2.TransReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Translater', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
